### ISSUE TITLE
and there is no function gamma?

### ISSUE THREAD

**Issue by shishaotang** [felixkylo82/options-pricing#2]

**Comment by felixkylo82** [comment]
It was to calculate ivs, theoretical prices.

**Comment by shishaotang** [comment]
ok，so how can I calculate gamma？thanks

**Comment by felixkylo82** [comment]
I am adding you a contributor and thank for your enhancement.

**Comment by felixkylo82** [comment]
I got you wrong. Mathematically,  Gamma is to diffrantiate Delta once respective to stock price.

**Comment by shishaotang** [comment]
ok， I understand，thank you very much
